name: develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: Cache Build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/build
          ~/target
          $CARGO_HOME$/bin/
          $CARGO_HOME$/registry/index/
          $CARGO_HOME$/registry/cache/
          $CARGO_HOME$/git/db/
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: FMT
      run: cargo fmt -- --check